### ISSUE TITLE
This node can only be instantiated once.

### ISSUE THREAD

**Issue by modulator100** [Seeed-Studio/node-red-contrib-sscma#2]
I get the following error message when i add a new SSCMA client type "This node can only be instantiated once." 
There are no existing sccma types. I fully uninstalled and reinstalled sscma but still the same error appears.
There is an mqtt server running, independent if I enter correct or wrong settings, the error still appears.

Node-Red 4.0.5
Rapsberry Pi 5
Operating System: Debian GNU/Linux 12 (bookworm)  
Kernel: Linux 6.6.62+rpt-rpi-2712
Architecture: arm64

<img width="978" alt="Picture 2024-12-28 um 11 42 48" src="https://github.com/user-attachments/assets/6c680300-a823-49cd-a600-1e4212c7b705" />

**Comment by LynnL4** [comment]
Hi，
Sorry for the inconvenience, but currently, node-red-contrib-sscma only supports recamera.
https://wiki.seeedstudio.com/recamera_getting_started/#set-up-the-working-environment
